// Re-export all database tables and types from shared/schema.ts
// This maintains backwards compatibility with existing server imports

export {
  users,
  subscriptions,
  predictions,
  modelWeights,
  learningLogs,
  bankrollAlerts,
  betHistory,
  userAnalytics,
  notificationPreferences,
  sportsbookAccounts,
  responsibleGaming,
  betBackups,
  oddsSnapshots,
  taxRecords,
  tokenStore,
  usersRelations,
  subscriptionsRelations,
  predictionsRelations,
  insertUserSchema,
  insertSubscriptionSchema,
  insertPredictionSchema,
  insertModelWeightSchema,
  insertLearningLogSchema,
  insertBankrollAlertSchema,
  insertBetHistorySchema,
  insertUserAnalyticsSchema,
  insertNotificationPreferencesSchema,
  insertSportsbookAccountSchema,
  insertResponsibleGamingSchema,
  insertBetBackupSchema,
  insertOddsSnapshotSchema,
  insertTaxRecordSchema,
} from "@shared/schema";

export type {
  InsertUser,
  User,
  InsertSubscription,
  Subscription,
  InsertPrediction,
  Prediction,
  InsertModelWeight,
  ModelWeight,
  InsertLearningLog,
  LearningLog,
  InsertBankrollAlert,
  BankrollAlert,
  InsertBetHistory,
  BetHistory,
  InsertUserAnalytics,
  UserAnalytics,
  InsertNotificationPreferences,
  NotificationPreferences,
  InsertSportsbookAccount,
  SportsbookAccount,
  InsertResponsibleGaming,
  ResponsibleGaming,
  InsertBetBackup,
  BetBackup,
  InsertOddsSnapshot,
  OddsSnapshot,
  InsertTaxRecord,
  TaxRecord,
} from "@shared/schema";
