// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/attention-model/TheDailyBrief.tsx": () => import("../components/mockups/attention-model/TheDailyBrief.tsx"),
  "./components/mockups/attention-model/TheOracle.tsx": () => import("../components/mockups/attention-model/TheOracle.tsx"),
  "./components/mockups/attention-model/TheWarRoom.tsx": () => import("../components/mockups/attention-model/TheWarRoom.tsx"),
  "./components/mockups/dashboard-usability/AccessibilityReadability.tsx": () => import("../components/mockups/dashboard-usability/AccessibilityReadability.tsx"),
  "./components/mockups/dashboard-usability/InformationHierarchy.tsx": () => import("../components/mockups/dashboard-usability/InformationHierarchy.tsx"),
  "./components/mockups/dashboard-usability/InteractionAffordance.tsx": () => import("../components/mockups/dashboard-usability/InteractionAffordance.tsx")
};
