name: Timestamp

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Print timestamp
        run: date -u
